# Generated by Django 4.2.23 on 2025-08-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="academic_status",
            field=models.CharField(
                blank=True,
                choices=[("未毕业", "未毕业"), ("已毕业", "已毕业"), ("在职", "在职")],
                max_length=20,
                null=True,
                verbose_name="学业状态",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="current_major",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="所学专业"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="current_school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="就读院校"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="exam_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="考研年份"),
        ),
        migrations.AddField(
            model_name="student",
            name="grade_rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("前15%", "前15%"),
                    ("前30%", "前30%"),
                    ("前50%", "前50%"),
                    ("后50%", "后50%"),
                ],
                max_length=20,
                null=True,
                verbose_name="专业成绩排名",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="study_mode",
            field=models.CharField(
                blank=True,
                choices=[("全日制", "全日制"), ("非全日制", "非全日制")],
                max_length=20,
                null=True,
                verbose_name="就读方式",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="target_city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="目标城市"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="target_major_category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="目标专业类别"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("985", "985高校"),
                    ("211", "211高校"),
                    ("双一流", "双一流高校"),
                    ("普通院校", "普通院校"),
                ],
                max_length=20,
                null=True,
                verbose_name="目标院校类型",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="education_path",
            field=models.CharField(
                choices=[("专升本", "专升本"), ("考研", "考研"), ("艺考", "艺考")],
                default="考研",
                max_length=20,
                verbose_name="教育路径",
            ),
        ),
    ]
