# Generated by Django 4.2.23 on 2025-08-03 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommendation",
            "0002_student_academic_status_student_current_major_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="academic_preference",
            field=models.BooleanField(default=False, verbose_name="偏好学术研究"),
        ),
        migrations.AddField(
            model_name="student",
            name="career_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("学术科研", "学术科研"),
                    ("企业就业", "企业就业"),
                    ("公务员", "公务员"),
                    ("事业单位", "事业单位"),
                    ("外企", "外企"),
                    ("大厂", "大厂"),
                    ("创业", "创业"),
                    ("其他", "其他"),
                ],
                max_length=50,
                null=True,
                verbose_name="目标方向",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="economic_condition",
            field=models.CharField(
                blank=True,
                choices=[("高", "可接受高学费/高生活成本"), ("中", "适中学费/生活成本"), ("低", "需要考虑经济条件")],
                max_length=20,
                null=True,
                verbose_name="经济条件",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="english_level",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="英语水平"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="estimated_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="预估分数"),
        ),
        migrations.AddField(
            model_name="student",
            name="gpa",
            field=models.FloatField(blank=True, null=True, verbose_name="GPA"),
        ),
        migrations.AddField(
            model_name="student",
            name="gpa_ranking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("前15%", "前15%"),
                    ("前30%", "前30%"),
                    ("前50%", "前50%"),
                    ("后50%", "后50%"),
                ],
                max_length=20,
                null=True,
                verbose_name="GPA排名",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="math_level",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="数学基础"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="overseas_plan",
            field=models.BooleanField(default=False, verbose_name="海外发展计划"),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="往年考试分数"),
        ),
        migrations.AddField(
            model_name="student",
            name="strategy_preference",
            field=models.CharField(
                choices=[("保守", "保守策略"), ("均衡", "均衡策略"), ("冲刺", "冲刺策略")],
                default="均衡",
                max_length=20,
                verbose_name="策略偏好",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="target_cities",
            field=models.TextField(blank=True, null=True, verbose_name="目标城市"),
        ),
        migrations.AddField(
            model_name="student",
            name="target_companies",
            field=models.TextField(blank=True, null=True, verbose_name="目标公司类型"),
        ),
        migrations.AlterField(
            model_name="student",
            name="target_city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="优先城市"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="total_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(750),
                ],
                verbose_name="高考总分",
            ),
        ),
    ]
