# Generated by Django 4.2.23 on 2025-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommendation",
            "0003_student_academic_preference_student_career_direction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="majors",
            field=models.ManyToManyField(
                blank=True,
                related_name="schools",
                to="recommendation.major",
                verbose_name="开设专业",
            ),
        ),
    ]
